name: Upgrade all requirements

on:
  schedule:
    - cron: '45 21 * * *'
  workflow_dispatch:

jobs:
  pip-compile-upgrade:
    name: Upgrade all requirements
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2.4.0

      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: '3.10.2'

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Upgrade all requirements
        run: pip-compile --upgrade

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          body: Upgrade all dependencies with `pip-compile --upgrade`
          branch: pip-compile-upgrade
          commit-message: Upgrade all dependencies with `pip-compile --upgrade`
          delete-branch: true
          title: Upgrade all dependencies with `pip-compile --upgrade`
          token: ${{ secrets.personal_token }}
